name: Mirror Branch
description: Mirror the triggering branch to a target branch

branding:
  icon: git-branch
  color: blue

inputs:

  token:
    description: GitHub API access token
    required: false
    default: ${{ github.token }}

  target:
    description: Name of the target branch
    required: false
    default: "main"

runs:
  using: node20
  main: dist/index.js